--CREATE TABLE Users (id INTEGER PRIMARY KEY AUTOINCREMENT,
--                    username TEXT UNIQUE NOT NULL,
--                    password TEXT NOT NULL);
--CREATE TABLE Exerciseslist (
--    id INTEGER PRIMARY KEY AUTOINCREMENT,
--    exercisename TEXT NOT NULL,
--    reps INTEGER,
--    sets INTEGER,
--    weight REAL,
--    rest_timer INTEGER DEFAULT 60
--    );